name: BE-CI
run-name: BE-CI

on:
  pull_request:
    branches:
      - 'develop'
    paths:
        - backend/**
  push:
    branches:
      - feat/ci-cd
defaults:
  run:
    working-directory: ./backend
jobs:
  run-quanlity-code:
    runs-on: ubuntu-latest #Runner free
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using docker to check convention code
        run: |
          echo "Start lint...."
          echo "Install tool..." #Install tool if github actio
name: BE deploy staging branch
run-name: BE deploy staging branch
on:
  push:
    branches:
      - 'staging'
    paths:
    - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: [self-hosted,backend-server-staging] # tag in server-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls
          echo "Build image"